#!/bin/bash

PRINTF_FORMAT="%8s  "

if [ $# -eq 1 ]; then
	cd $1;
fi

# Get extensions
ext=$( ls | sed -e "s/^.*\(\..*\)$/\1/g" | sed -e "s/^[^.]\+$//g" | sort -u )

# Remove extensions with *~
ext=$( echo $ext | tee | sed -e "s/[^ ]*~//g" )

for i in $ext; do
	tput setaf 9
	tput setab 7
	printf "$PRINTF_FORMAT" "*"$i
	tput sgr0
	echo -n " "
	ls --color=auto *$i
done

noext=$( ls | sed "s/^.*\..*$//" )

if ! [ -z "$noext" ]; then
	tput setaf 9
	tput setab 7
	printf "$PRINTF_FORMAT" "others"
	tput sgr0
	echo -n " "
	echo $noext | xargs ls --color=auto -d
fi
