#!/bin/bash

# elf_qpush
#
# This program creates a queue on current directory, using arguments or standard input.
# 
# If arguments are given, all arguments are placed on the queue, with first argument being
#   in the front of the queue.
# If arguments are not given, then standard input is read, and each string read is placed
#   in the queue, in the order of receival of such strings.
#

FILENAME="queue.elf"

rm -vf $FILENAME

if [[ "$@" != "" ]]; then
	# If arguments are given, we read arguments
	echo "Reading arguments"
	for i in "$@"; do
		echo $i >> $FILENAME;
	done
else
	# If arguments are not given, we read stdin
	echo "Reading stdin"
	for i in $( cat ); do
		echo $i >> $FILENAME;
	done
fi

